### PR TITLE
ctu-clang8 patches

### PR DESCRIPTION
**Pull request by balazske**

### CODE REVIEW

**Review by martong — COMMENTED** [review]
Looks good, but please wait with the merge because I am working on the ci now (ci2).

**Comment by balazske** [comment]
One test (Misc/warning-flags.c) fails, probably because the new warning in #663 . Warning count should be updated to 75.

**Comment by martong** [comment]
> One test (Misc/warning-flags.c) fails, probably because the new warning in #663 . Warning count should be updated to 75.

Could you please fix the warning count too?

**Comment by balazske** [comment]
The test says that we should add a -W flag for the new warnings, is this not applicable for ASTImporter case (even then it is good to have some documentation about it)?

**Comment by martong** [comment]
> The test says that we should add a -W flag for the new warnings, is this not applicable for ASTImporter case (even then it is good to have some documentation about it)?

We can do that later if needed. But in previous branches (ctu-clang7, ctu-clang6) we have not added the -W flag for the new warnings, instead we changed this count.

**Review by martong — APPROVED** [review]

**Comment by balazske** [comment]
#659 #660 #663 #664 are still missing, can I add these (in this PR)?

**Comment by martong** [comment]
> #659 #660 #663 #664 are still missing, can I add these (in this PR)?

Well, I merged it already, could you please add them in a new PR?

**Pull request merged**
