### PR TITLE
Add check for incompatible lang opts

### LINKED ISSUE #36: Include more information in the "mangled name" or document limitations
Right now the mangled name is extended with info about the architecture. This helps when the project is build for multiple architectures. This does not help however when the software is built for the same architecture for multiple OSes.
We should either "force" the user via documentation to not to do builds for multiple targets when running the analysis or we should include os and environment information in the unique name of the functions.

### PR DESCRIPTION
**Pull request by martong**
Closes #36

### CODE REVIEW

**Comment by martong** [comment]
Related to https://github.com/Ericsson/codechecker/pull/1258

**Comment by martong** [comment]
Having different sign of the type 'char' can result in structural in-equivalences in `ASTImporter` which in turn can result in invalid and in-equivalent imported AST!
I think similar problem may arise if other language options are different (e.g importing into C++11 from C++98), so on a long term we should error on other lang options too.

**Comment by martong** [comment]
Note, these errors became visible by properly enabling the `isStructuralMatch` assertion, see issue #222 .

**Comment by whisperity** [comment]
What happens in this case when I'm not running the analyzer but instead just building my executables? Do I get a linker error? Do I get a binary which constains UB around these issues?

**Comment by martong** [comment]
@whisperity Probably you'll get a linker error, or if it links then UB.

**Comment by martong** [comment]
I changed the check for different target options now. This is a stronger check than the 'char' sign check, but includes that check implicitly. About languages: It is legal to import C AST into a C++ AST, so lang can be different, we will not check for that ATM.
Still, importing C++ into C could be a (tragic) problem. @Xazax-hun, @whisperity what's your opinion about handling different languages and lang options?

**Comment by whisperity** [comment]
Could it? I mean, from the developer perspective, I believe C code can link against C++ libraries in cases where it isn't UB. An `extern C` method specifier only disables overloading and overrules the mangling system, it does not restrict the method into the C subset of language features.
Question is, how prominent such constructs really are in the wild?

**Comment by martong** [comment]
Related: issue #36

**Comment by Xazax-hun** [comment]
> It is legal to import C AST into a C++ AST, so lang can be different, we will not check for that ATM. Still, importing C++ into C could be a (tragic) problem.
I agree. But there are valid cases to import C++, e.g. calling extern C functions. 

Unfortunately, both ways can be tricky. Because, the checks and even more might rely on language options. We end up visiting code with the wrong language opts. I am not sure how often will this be a problem.

It is good to diagnose the target mismatch. It might uncover issues within the CodeChecker.

**Comment by Xazax-hun** [comment]
Another note, isn't it too restrictive to check for all of the triple to be the same? Are there valid cases  when only the last part of the tripple differs?

**Comment by martong** [comment]
@Xazax-hun 
First of all, `Triple` is not a literal triple, It has 6 important members we do check:
```
  bool operator==(const Triple &Other) const {
    return Arch == Other.Arch && SubArch == Other.SubArch &&
           Vendor == Other.Vendor && OS == Other.OS &&
           Environment == Other.Environment &&
           ObjectFormat == Other.ObjectFormat;
  }
```
 I think the safest is to check all 6 members of the triple to be equal (as it is in `operator==`). I am afraid that even if just the environment is different we could experience the char signedness problem which eventually could lead a corrupt AST with nodes of Type<char> and Type<signed char>. And similarly to the other members in `Triple`.

**Pull request merged**
