### PR TITLE
Added macro expansions to the plist output

### PR DESCRIPTION
**Pull request by Szelethus**
This is an experimental implementation for displaying macro expansion in the plist output. This is little more than a copy-paste from `HTMLRewrite.cpp`, which re-lexes and preprocesses the entire file. While this definitely should be regarded as a huge hack and only a temporary solution, it should be stable enough for testing.

### CODE REVIEW

**Comment by dkrupp** [comment]
Can one of the admins verify this patch?

**Comment by martong** [comment]
run tests

**Comment by martong** [comment]
run tests
looks like tmux analysis hangs, this may be because of a restart of jenkins, so just restarted the test

**Comment by martong** [comment]
Seems like the CTU analysis is slowed down terribly by this patch :( Even though for the first sight it seems an independent change. Could you please have a look? I can help you if you got stuck. 
 http://ci1.codechecker.gic.ericsson.se:8080/job/ctu_pipeline_pullrequest/37
The main branch (ctu-clang6) currently runs quite fast even on the whole pipeline, not just on the PR pipeline: http://ci1.codechecker.gic.ericsson.se:8080/job/ctu_pipeline/

**Comment by martong** [comment]
Looks like this is not a clang problem, but rather a problem with `csa_testbench` which tries to parse the plists (I guess).
the python process got stuck and uses 100% CPU:
```
clang-j+  6568  6551 95 Aug21 ?        13:49:44 python /var/jenkins_home/ctu_pipeline_aux/csa-testbench/run_experiments.py --config /var/jenkins_home/mustpass_projects_jenkins.json --jobs 8 --fail_on_assert
```

**Comment by Szelethus** [comment]
I completely reinvented this and posted it on Phabricator: https://reviews.llvm.org/D52742.
Looking at the implementation though, it should be compatible with earlier clang versions.

**Pull request closed without merging**
