### PR TITLE
WIP: addHiddenDecl assert fix

### PR DESCRIPTION
**Pull request by balazske**
(experimental) fix for an assertion:
clang-5.0: llvm/tools/clang/lib/AST/DeclBase.cpp:1380: void clang::DeclContext::addHiddenDecl(clang::Decl*): Assertion `!D->getNextDeclInContext() && D != LastDecl && "Decl already inserted into a DeclContext"' failed.

### CODE REVIEW

**Comment by balazske** [comment]
wip

**Comment by whisperity** [comment]
What's a `HiddenDecl`? Also, you should make sure your commits are using an email that is added to your github user currently the commit shows up as an unknown author.

**Comment by martong** [comment]
Fixes #275

**Comment by martong** [comment]
@whisperity 
Actually, this problem has nothing to do with the "hidden" property.
The trace comes from `DeclContext::addDeclInternal` which consist of calling `addHiddenDecl` and putting the decl into the lookup table. `addHiddenDecl` in itself adds the declaration but does not add that to the lookup tables, thus the name "hidden".

**Comment by balazske** [comment]
closing pull request because problems with tests ("make check-all" does not pass)

**Pull request closed without merging**
