### PR TITLE
Clean up experimental features

### PR DESCRIPTION
**Pull request by gamesh411**
Fixes(#158)

Please review to make sure the changes are correct.
I haven't found usages of the `xtu-build-graph.py`, is that possible?

### CODE REVIEW

**Comment by Xazax-hun** [comment]
Looks good so far.

Could you also remove the bool AnalyzerOptions::shouldReanalyzeCTUVisitedFns() config option from clang and all the related code? Now we should always reanalyze CTU visited functions. 
Also the scripts should no longer pass the related flag to the analyzer.

**Comment by gamesh411** [comment]
Updated the pull request branch. I would like to ask for help with the semantics of this change. Does this solution right now (with only the removal of the option and the branch condition, and no further changes) enable the norevisit routine right now? (as opposed to disable it)

**Comment by Xazax-hun** [comment]
The behavior should be the opposite, so VisitedFunc.txt is no longer needed.

**Comment by Xazax-hun** [comment]
Also `ReanalyzeCTUVisitedFns` should be removed from the header file, along with the declaration.

**Comment by Xazax-hun** [comment]
Maybe you should also check, how scan-build-py work when CTU is used, and also do not append this option to the analyzer arguments there.

**Comment by dkrupp** [comment]
Do we need xtu-analyze and xtu-build scripts at all?
Codechecker master version now contains everything that we need to run cross tu analysis.
I think maintaining these scripts is an unnecessary extra work.

I recommend removing these scripts and update the wiki with the info that the CTU functionality can be used with CodeChecker newest version.

**Comment by gamesh411** [comment]
I have updated my branch to match the original declaration handling logic of clang.

**Comment by Xazax-hun** [comment]
Great! Thanks!

**Pull request merged**
