### PR TITLE
[ASTImporter] Separate test files

### PR DESCRIPTION
**Pull request by martong**
Move generic redecl chain tests and visibility tests into their own separate test files.

### CODE REVIEW

**Comment by balazske** [comment]
Is it possible to have the implementation of the common things in a separate file instead of the ASTImporterFixtures.h ?

**Comment by martong** [comment]
Yes it is possible.

**Comment by martong** [comment]
run tests

**Comment by martong** [comment]
Update: Added a an impl file for ASTImporterFixtures.h

**Review by balazske — APPROVED** [review]
I assume that the copy-paste operations were correct.

**Pull request merged**
